In [1]:
# # Data Preprocessing
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv(r'C:\InhouseInternship\majorproject7\Test set.csv')

In [3]:
print(dataset)

         Height     Weight     Sex
0    146.323241  59.861065  Female
1    175.695412  77.863687    Male
2    183.216164  72.131992    Male
3    184.245269  77.546000    Male
4    132.302261  55.188496  Female
..          ...        ...     ...
200  155.090314  77.248911  Female
201  149.175907  93.231692    Male
202  168.030874  63.640623  Female
203  172.608090  55.189983    Male
204  145.082128  45.583285  Female

[205 rows x 3 columns]


In [4]:
#Checking Missing values
dataset.isnull().sum()

Height    0
Weight    0
Sex       0
dtype: int64

In [5]:
# # Removing index column
# dataset = dataset.dropna()
dataset

Height     Weight     Sex
0    146.323241  59.861065  Female
1    175.695412  77.863687    Male
2    183.216164  72.131992    Male
3    184.245269  77.546000    Male
4    132.302261  55.188496  Female
..          ...        ...     ...
200  155.090314  77.248911  Female
201  149.175907  93.231692    Male
202  168.030874  63.640623  Female
203  172.608090  55.189983    Male
204  145.082128  45.583285  Female

[205 rows x 3 columns]

In [6]:
dataset.describe()

Height      Weight
count  205.000000  205.000000
mean   160.874125   69.927028
std     15.171040   15.462396
min    123.007006   34.726666
25%    148.942667   58.583137
50%    161.749388   69.544469
75%    172.608090   77.964667
max    199.282251  129.410122

In [7]:
# Encoding Categorical data:
# # Encoding the Independent Variable
# from sklearn.preprocessing import LabelEncoder
# labelencoder_X = LabelEncoder()
# X[:, 6] = labelencoder_X.fit_transform(X[:, 6])

In [8]:
# Extracting dependent and independent variables:
# Extracting independent variable:
X = dataset.iloc[:,0:2].values
# Extracting dependent variable:
y = dataset.iloc[:, 2].values

In [9]:
# Encoding Categorical data:
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder
labelencoder_y = LabelEncoder()
labelencoder_y.fit(["Male","Female"])
y = labelencoder_y.fit_transform(y)

In [10]:
print(X)

[[146.3232413   59.861065  ]
 [175.6954121   77.86368697]
 [183.2161637   72.13199162]
 [184.2452685   77.54599954]
 [132.3022607   55.18849649]
 [149.8639136   66.05565459]
 [191.1730884   83.63133864]
 [135.4071744   47.01445695]
 [184.9957625   71.93582824]
 [179.9908867   65.92079489]
 [186.1618374   83.72019383]
 [177.784335    51.59443143]
 [124.5761544   49.49065937]
 [135.0845874   57.01715684]
 [161.783083    63.11811732]
 [147.1984523   74.90954714]
 [168.6195333   68.71086764]
 [180.3799948   58.5831375 ]
 [172.9806484   91.76506667]
 [183.2740005   83.53897404]
 [135.8408238   75.15031468]
 [177.3010401   61.54651   ]
 [170.228071    63.16246219]
 [141.8363614   45.4665998 ]
 [151.4646936   51.1065089 ]
 [150.2536868   56.38212115]
 [123.0070061   66.68550969]
 [170.8142259   72.87114003]
 [179.5604019   93.3795254 ]
 [146.7985959   58.96877805]
 [145.830298    91.71072835]
 [144.981023    70.54812663]
 [139.3907781   58.18591881]
 [182.6131284   90.55450022]
 [178.4496356 

In [11]:
print(y)

[0 1 1 1 0 0 1 0 1 1 1 1 0 0 0 0 1 1 1 1 0 1 1 0 0 0 0 1 1 0 0 1 0 1 1 1 0
 1 0 1 0 0 0 1 1 0 1 1 1 0 1 1 0 1 1 1 1 1 1 0 0 0 1 1 1 1 0 0 1 1 1 1 0 0
 1 0 0 1 0 0 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 1 1 0 0 1 1 0 0 1 1 0 0 0 0 0 0
 0 0 0 0 0 0 1 0 0 0 1 1 0 1 0 1 1 1 0 0 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0
 1 1 0 0 1 1 1 1 0 0 1 0 1 1 1 1 0 0 0 1 1 1 0 1 0 1 0 1 1 0 1 1 0 1 0 1 1
 0 1 1 1 1 0 1 0 1 1 0 0 0 0 0 0 1 0 1 0]


In [12]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [13]:
print(X_train)

[[132.3022607   55.18849649]
 [156.8690279   53.62286242]
 [158.272415    48.97376511]
 [164.1230059   41.23383545]
 [183.0966467   64.05785271]
 [123.0070061   66.68550969]
 [148.0261077   49.21201967]
 [199.2822511   55.75179928]
 [152.3723814   73.42231034]
 [184.9957625   71.93582824]
 [155.867935    53.30410127]
 [180.5159267   70.42488418]
 [152.7088563   62.79598838]
 [155.0623811   79.42228181]
 [145.2916488   50.31307691]
 [166.3135265   88.13290343]
 [133.2099703   65.67113792]
 [171.4205329   80.40997588]
 [151.4646936   51.1065089 ]
 [145.830298    91.71072835]
 [169.2229144   83.21845422]
 [135.7625193   39.98973038]
 [147.2221773   76.70733287]
 [155.754493    86.9498469 ]
 [150.581321    60.71624655]
 [180.7420372  103.3905654 ]
 [183.2740005   83.53897404]
 [162.9186952   77.30707502]
 [147.2088207   71.91470902]
 [180.9764798   95.59478219]
 [178.8946419   78.25158421]
 [164.2692232   61.26559153]
 [161.3928705   51.19553074]
 [160.8713684   49.65055203]
 [147.9065279 

In [14]:
print(X_test)

[[156.7976193   68.21134945]
 [190.2616152   97.10252458]
 [149.8639136   66.05565459]
 [172.9806484   91.76506667]
 [170.6105691   54.68173273]
 [139.0659727   55.14056088]
 [142.5393447   71.64057998]
 [165.4790635   86.54622202]
 [171.0917634   72.24031272]
 [182.6131284   90.55450022]
 [124.5761544   49.49065937]
 [142.8596964   58.79075666]
 [175.2433961   77.13018201]
 [143.3310166   71.15222384]
 [162.2114966   53.98530301]
 [164.8711385   75.46953342]
 [134.0932725   60.88158179]
 [135.4071744   47.01445695]
 [166.950541    68.60650747]
 [165.0537385   90.72013328]
 [174.3396578   87.15967177]
 [150.3120371   72.23105588]
 [139.3309187   50.94727899]
 [171.0282427   74.7954068 ]
 [176.6875383   86.28422599]
 [144.9223785   65.81607146]
 [157.9004943   46.14417081]
 [158.5757835   83.6079361 ]
 [173.7816213   54.46835757]
 [153.5540268   64.21426629]
 [177.2710736   75.99564021]
 [154.1159173   82.4932717 ]
 [138.5758889   75.88078275]
 [177.0294219   86.0358905 ]
 [168.0598835 

In [15]:
print(y_test)

[0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 0 1 1 1 0 0 1 1 0 0 0 1 0 1 1 0 1 1 1 1
 1 1 1 1]


In [16]:
print(y_train)

[0 1 0 1 1 0 0 1 1 1 0 1 0 0 0 1 0 1 0 0 1 0 0 1 0 1 1 1 0 1 1 1 1 0 0 1 0
 1 0 1 0 1 0 0 1 1 1 0 1 1 1 0 0 1 1 1 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 1 1 1
 0 1 0 1 1 0 0 1 0 0 0 0 0 0 1 0 1 1 1 0 1 0 1 1 0 1 1 0 0 1 1 1 1 0 0 0 0
 0 0 1 0 1 1 0 1 1 1 0 0 1 1 1 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 1 0 1
 1 1 1 1 1 1 0 1 1 1 0 0 0 1 1 0]


In [17]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import GaussianNB
classifier_NB = GaussianNB()
classifier_NB.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier_NB.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

# calculate Accuracy
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))



Confusion matrix: 
[[16  1]
 [ 2 22]]
Accuracy: 92.68


In [29]:
filename = 'model_nb.pkl'
pickle.dump(classifier_NB, open(filename, 'wb'))

In [18]:
import pickle
print("[INFO] Saving model...")
# Save the trained model as a pickle string.
saved_model=pickle.dump(classifier_NB,open('major_NB.pkl', 'wb'))
# Saving model to disk

[INFO] Saving model...


In [19]:
# Fitting K-NN to the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier_KNN= KNeighborsClassifier()
classifier_KNN.fit(X_train,y_train)

# Predicting the Test set results
y_pred = classifier_KNN.predict(X_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

# calculate Accuracy
#               Y_pred
#             0       1
#          0[64     4(FP)]  Type 1 Error
# y-test   1[3(FN)     29]  Type 2 Error
# Accuracy 64+29/64+4+3+29
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))

Confusion matrix: 
[[17  0]
 [ 2 22]]
Accuracy: 95.12


In [27]:
filename = 'model_knn.pkl'
pickle.dump(classifier_KNN, open(filename, 'wb'))

In [21]:
# Fitting Decision Tree Classification to the Training set
from sklearn.tree import DecisionTreeClassifier
classifier_DT = DecisionTreeClassifier(criterion = 'entropy', random_state = 42)
classifier_DT.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier_DT.predict(X_test)
print(y_pred)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))


[1 1 0 1 0 0 1 1 0 1 0 0 1 1 0 0 0 0 1 1 1 0 0 1 1 0 0 1 1 1 1 0 0 1 0 1 1
 0 0 0 1]
Confusion matrix: 
[[12  5]
 [ 8 16]]
Accuracy: 68.29


In [28]:
filename = 'model_dt.pkl'
pickle.dump(classifier_DT, open(filename, 'wb'))

In [23]:
# Fitting SVM to the Training set LINEAR
from sklearn.svm import SVC
classifier_linear = SVC(kernel = 'linear', random_state = 0)
classifier_linear.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier_linear.predict(X_test)
print(y_pred)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

# calculate Accuracy
#   0   1
# 0[66  2(FP type 1)]
#1 [8(FN Type 24) 23]
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))

[0 1 0 1 1 0 0 1 1 1 0 0 1 0 0 1 0 0 1 1 1 0 0 1 1 0 0 1 1 0 1 0 0 1 1 1 1
 1 1 1 1]
Confusion matrix: 
[[16  1]
 [ 1 23]]
Accuracy: 95.12


In [30]:
filename = 'model_linear.pkl'
pickle.dump(classifier_linear, open(filename, 'wb'))

In [24]:
import pickle
print("[INFO] Saving model...")
# Save the trained model as a pickle string.
saved_model=pickle.dump(classifier_linear,open('major_SVM_linear.pkl', 'wb'))
# Saving model to disk

[INFO] Saving model...


In [25]:
# Training the Random Forest Classification model on the Training set
from sklearn.ensemble import RandomForestClassifier
classifier_Random = RandomForestClassifier(n_estimators = 200, criterion = 'entropy', random_state = 0)
classifier_Random.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier_Random.predict(X_test)
print(y_pred)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print('Confusion matrix: ')
print(cm)

# calculate Accuracy
from sklearn.metrics import accuracy_score
print('Accuracy: %.2f' % (accuracy_score(y_test, y_pred)*100))



[1 1 0 1 1 0 0 1 1 1 0 0 1 0 0 0 0 0 1 1 1 0 0 1 1 0 0 0 1 0 1 0 0 1 0 1 1
 1 1 1 1]
Confusion matrix: 
[[16  1]
 [ 3 21]]
Accuracy: 90.24


In [31]:
filename = 'model_random.pkl'
pickle.dump(classifier_Random, open(filename, 'wb'))

In [26]:
import pickle
print("[INFO] Saving model...")
# Save the trained model as a pickle string.
saved_model=pickle.dump(classifier_Random,open('major_RF.pkl', 'wb'))
# Saving model to disk

[INFO] Saving model...
